# Generated by Django 4.2.1 on 2024-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_cars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
