# Generated by Django 4.2.1 on 2024-02-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_tagpost_alter_cars_cat_cars_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='ceo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.ceo'),
        ),
    ]
