name: Django CI with Vault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Vault
      uses: hashicorp/vault-action@v3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}

    - name: Retrieve SECRET_KEY from Vault
      id: secret_key
      run: |
        export SECRET_KEY=$(vault kv get -field=SECRET_KEY secret/django)
        echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV  # Сохраняем в переменной окружения

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r sitetest/requirements.txt

    - name: Run Tests
      run: |
        python sitetest/manage.py test


