name: Django CI with Vault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      - name: Retrieve SECRET_KEY from Vault
        id: secret_key
        run: |
          export SECRET_KEY=$(vault kv get -field=SECRET_KEY secret/django)
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV  # Сохраняем в переменной окружения

  install_dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r sitetest/requirements.txt

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-dependencies
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-dependencies

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore dependencies from cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.install_dependencies.outputs.cache-key }}  # Используем ключ из предыдущего job

      - name: Run Django tests
        run: |
          python sitetest/manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v4

      # Восстанавливаем зависимости (если они нужны для деплоя)
      - name: Restore dependencies from cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ needs.install_dependencies.outputs.cache-key }}

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}  # Передаем SECRET_KEY для деплоя
