name: Django CI with Vault

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      # Шаг 1: Проверка кода из репозитория
      - uses: actions/checkout@v4

      # Шаг 2: Настройка Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Шаг 3: Настройка Vault
      - name: Set up Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}

      # Шаг 4: Получение SECRET_KEY из Vault
      - name: Retrieve SECRET_KEY from Vault
        id: secret_key
        run: |
          export SECRET_KEY=$(vault kv get -field=SECRET_KEY secret/django)
          echo "SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        continue-on-error: false

  install_dependencies:
    runs-on: ubuntu-latest
    needs: setup  # Этот job зависит от job 'setup'
    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Check out code
        uses: actions/checkout@v4

      # Шаг 2: Создание виртуального окружения
      - name: Create and activate virtual environment
        run: |
          python -m venv venv  # Создаем виртуальное окружение
          source venv/bin/activate  # Активируем виртуальное окружение
          python --version  # Проверяем версию Python
          which python  # Проверяем путь до активированного Python
          pip --version  # Проверяем версию pip
          pip freeze  # Проверяем установленные пакеты

      # Шаг 3: Кэширование зависимостей
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Шаг 4: Установка зависимостей
      - name: Install Python dependencies
        run: |
          source venv/bin/activate  # Активируем виртуальное окружение
          python -m pip install --upgrade pip
          pip install -r sitetest/requirements.txt

  run_tests:
    runs-on: ubuntu-latest
    needs: install_dependencies  # Этот job зависит от job 'install_dependencies'
    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Check out code
        uses: actions/checkout@v4

      # Шаг 2: Запуск тестов Django
      - name: Run Django tests
        run: |
          source venv/bin/activate  # Активируем виртуальное окружение
          python sitetest/manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: run_tests  # Этот job зависит от run_tests
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy to production (placeholder)
        run: |
          echo "Deploying to production..."
          # Здесь может быть команда для деплоя на сервер, например:
          # ssh user@server 'bash deploy.sh'
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}  # Передаем SECRET_KEY для деплоя
