name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create virtual environment
      run: |
        python -m venv venv
    - name: Install dependencies in virtual environment
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r sitetest/requirements.txt
    - name: Verify Django installation
      run: |
        source venv/bin/activate
        python -m django --version
    - name: Run Tests
      run: |
        source venv/bin/activate
        python sitetest/manage.py runserver
